# Generated by Django 4.0 on 2024-09-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_detectionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('is_elephant_present', models.BooleanField()),
                ('elephant_proportion', models.FloatField()),
                ('num_elephants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.CharField(max_length=255)),
                ('processed_video', models.CharField(max_length=255)),
                ('frame_count', models.IntegerField()),
                ('total_elephants', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectionFile',
        ),
        migrations.AddField(
            model_name='frameresult',
            name='video_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.videoanalysis'),
        ),
    ]
