# Generated by Django 4.2.17 on 2024-12-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_frameresult_videoanalysis_delete_detectionfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='status',
        ),
    ]
